# Generated by Django 5.0.3 on 2024-04-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generalsettings_delete_document_delete_education_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
    ]
