# Generated by Django 5.0.3 on 2024-04-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
