# Generated by Django 5.0.3 on 2024-05-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSetting',
        ),
    ]
