# Generated by Django 5.0.3 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_number',
            field=models.IntegerField(blank=True, default='', verbose_name='Reference Number'),
        ),
    ]
